export interface DataRow  {
    "_id": string;
    "5%": number;
    "10%": number;
    "15%": number;
    "20%": number;
    "25%": number;
    "30%": number;
    "35%": number;
    "40%": number;
    "45%": number;
    "50%": number;
    "55%": number;
    "60%": number;
    "65%": number;
    "70%": number;
    "75%": number;
    "80%": number;
    "85%": number;
    "90%": number;
    "95%": number;
    "75% Gain": number ;
    "95% Gain": number ;
    "98% Gain": number ;
    "99% Gain": number ;
    "Account Name": string;
    "Coin": string;
    "Container": string;
    "Final Equity": string;
    "IR": string;
    "Leverage": number;
    "Max": number;
    "Max UPNL": string;
    "Median Gain": number;
    "R:R": string | number;
    "Reserve": number;
    "S": string;
    "Status": string;
    "Year": number;
    "frame": string;
    "initial_risk": number;
    "max_slots": number;
    "phases": string;
  };