export interface DataRow  {
    upnl: number;
    equity: number;
    "_id": string;
    "5%": number;
    "10%": number;
    "15%": number;
    "20%": number;
    "25%": number;
    "30%": number;
    "35%": number;
    "40%": number;
    "45%": number;
    "50%": number;
    "55%": number;
    "60%": number;
    "65%": number;
    "70%": number;
    "75%": number;
    "80%": number;
    "85%": number;
    "90%": number;
    "95%": number;
    "75% Gain": number ;
    "95% Gain": number ;
    "98% Gain": number ;
    "99% Gain": number ;
    "account_name": string;
    "coin": string;
    "container": string;
    "final_balance": string;
    "ir": string;
    "leverage": number;
    "max_upnl": number;
    "median_gain": number;
    "alpha_ruin": string;
    "worst_ruin": string;
    "RR": string | number;
    "strategies": string ;
    "reserve": number;
    "S": string;
    "Status": string;
    "year": number;
    "frame": string;
    "initial_risk": number;
    "max_slots": number;
    "phases": string;
    "rsi_wma_day": string;
    "max_sizing": number;
   
  };